### PR TITLE
Fix versions for several runtime deps

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@jjhelmus, this fixed the runtime deps for 0.32.0

**Comment by isuruf** [comment]
This needs a build number bump

**Comment by ccordoba12** [comment]
You're totally right! Sorry for missing that.

**Comment by ccordoba12** [comment]
@jjhelmus, could give us a hand with this one? We want to update our minimal requirement on Spyder to this version for our next release, but we can't move forward because there are not conda packages for it yet.

Thanks for your help!

**Comment by jjhelmus** [comment]
@ccordoba12 Is there still need for 0.32.0 packages in `defaults` if 0.33.0 packages are available?

**Comment by ccordoba12** [comment]
No, there's no need for them now. Thanks for asking though.

**Pull request merged**
