### PR TITLE
Add "pip check" test

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for getting 0.32 out so speedily, looking forward to testing with it.

This is a low-priority addition of `pip check` (it passes, locally), and wouldn't _need_ a new build just for this, but I'd _love_ to see this get added if any other builds occur in the near term, just for the warm fuzzies.

### CODE REVIEW

**Comment by ccordoba12** [comment]
What does `pip check` do?

**Comment by bollwyvl** [comment]
`pip check` uses setuptools (presumably) to verify that every `install_requires` pin, of every installed python package, is satisfied. I am not entirely sure it checks `extras`, and is not configurable, so there can certainly be some false positives. However, I haven't yet found a package that passes `pip check` that still creates errors like `distribution not available`, etc. when `pkg_resources.iter_entry_points` gets called (even if something isn't "really" broken). Given that `pyls` uses that _extensively_, we've had lots of folk run into issues, especially if they try to install with conda, then start doing some pip on top of it to "fix" it.

There's some support for doing it [by default](https://github.com/conda-forge/conda-forge.github.io/issues/962), and really, it should be a `conda-build` feature, but there's very few reasons not to proactively start using it on a repo-by-repo basis if it provides value... and given the adventures with `ujson`, etc. I'd say this repo is a good candidate!

Some of those reasons:

- if installing `pip`, and its dependencies (e.g. `setuptools`), fulfills dependencies that otherwise wouldn't have been, you get a false-positive. 
  - On this package, for instance, because `pkg_resources` gets used, there should be a declared dependency on `setuptools`
    - the upstream doesn't declare it, though, as they probably don't test any way _other_ than installing their dependencies with `pip`.

- if something _is_ broken, it can be a very deep rabbit hole indeed
  - there are a (diminishing) number of older, stable packages that don't get rebuilt/tested often that actually have (potentially inaccurate) pins that didn't get added to the feedstocks

**Comment by ccordoba12** [comment]
Thanks for the very detailed explanation @bollwyvl!

Could you change the required version of one of our deps (e.g Jedi to `>=0.14.1,<0.16`) to see if `pip check` effectively detects an error there?

**Comment by bollwyvl** [comment]
Hey, at least it passed the linter!

**Comment by ccordoba12** [comment]
Nice!! Please remove your last commit so I can merge this one @bollwyvl.

And thanks again for your help!

**Comment by goanpeca** [comment]
So should we add setuptools on the install requires upstream?

**Comment by bollwyvl** [comment]
Well, like it said up top: this may not even need to be merged (or if so,
shouldn't bump the build).

Regarding the upstream setuptools dep: yes, it probably should!

Anyhow will so some plumbing later...

**Review by ccordoba12 — APPROVED** [review]
Thanks @bollwyvl!

**Pull request merged**
